### ISSUE TITLE
Expeditions: Limit types of military ships

### ISSUE THREAD

**Issue by Deenayd** [ogame-tbot/TBot#115]
Some military ships are painfully slow. It might be a good idea to select what types of military ships should be allowed in expeditions and what types should be avoided. Some players might decide to not use any military ships at all (only pathfinders).

**Comment by kokiddp** [comment]
there is ManualShips for that
i think the best composition for auto mode is already the implemented one

**Comment by Deenayd** [comment]
well, the point was to allow configurations like for example:
- automatic calculation of transport ships without automatic adding of military ships at all
- automatic calculation of transport ships with automatic adding of military ships but avoid adding bomber (as it's too slow)
