### ISSUE TITLE
[Sugestion] Release name : latest

### ISSUE THREAD

**Issue by Nhaakq** [ogame-tbot/TBot#121]
Hi, 

For the use of docker images or other automated deployments, it might be interesting to standardize the naming of packages to be able to access the latest packages more easily.

Currently working : 
https://github.com/ogame-tbot/TBot/releases/latest/download/TBot-v0.2.64-linux64.zip

Expected : 
https://github.com/ogame-tbot/TBot/releases/latest/download/TBot-linux64.zip

The naming of the zip package is the subject.
Thanks for reading my suggestion :)

N

**Comment by kokiddp** [comment]
i find it much neater with version tag in the name
for continuous integration you can retrieve all the artifacts attached to latest release via rest api and pick the one of your interest (regex?)
