### ISSUE TITLE
Solving AutoFarm issue

### ISSUE THREAD

**Issue by jordantete** [ogame-tbot/TBot#186]
Hi, 

First I want to thank you for your hard work on this project.

Do you plan to address the issue with the AutoFarm feature in a coming release ?

Best.

**Comment by 0xE232FE** [comment]
Hello @pownedjojo,

If you need AutoFarmer feature.

Until its patched here. You may use this release: https://github.com/0xE232FE/TBot/releases/tag/v3.0.4-login-fix3

best regards

**Comment by jordantete** [comment]
Hello @0xE232FE 

Thanks for your answer. 

Which release should I use ? The page you're pointing to show a 404 error 😢 

Best.

**Comment by 0xE232FE** [comment]
Excuse me the release wasn't public. Now it is!
