### ISSUE TITLE
Turtle mode - Build defence

### ISSUE THREAD

**Issue by MrBurrBurr** [ogame-tbot/TBot#21]
It would be nice to have a feature that would auto-build defence on each planet.

Settings part could look something like this:

```
"Turtle": {
	"Active": true,
	"CheckIntervalMin": 1,
	"CheckIntervalMax": 16,
	"Exclude": [],
	"DefenceToBuild": {
		"RocketLauncher": 20000,
		"LightLaser": 10000,
		and so on
	},
}
```

**Comment by kokiddp** [comment]
thank you for the suggestion, i'll think about that.

**Comment by MrBurrBurr** [comment]
I am not sure if this would be helpful. If an attack is incoming you hardly have enough time to build a big enough defence.

Or do I not understand what you mean with that property?

**Comment by emilianosalatino** [comment]
Just build destroyers, reapers and deaths stars... Bunkers are useless with sacs
