### ISSUE TITLE
question: how to use whitelist on defender mode

### ISSUE THREAD

**Issue by bengabay1994** [ogame-tbot/TBot#58]
to my understanding to insert a player into my whitelist (for example someone who helps me creating a moon and therefor attacking me.) I need to get his player ID, but I can't find anything that looks like a player ID on Ogame.
where do I get that player ID to insert it to the whitelist?

Thanks

**Comment by AssoMania** [comment]
Go here : https://www.mmorpg-stat.eu/
Look for the player you want to add in the whitelist and here you'll have the ID you're looking for.
