### ISSUE TITLE
ERROR failed to parse planet infos

### ISSUE THREAD

**Issue by malatia** [ogame-tbot/TBot#75]
Hi!
First, thanks for your work!
I'm trying your bot for the first time. Seems like he is conneting well to the acc and everything (can see my ranking, my planet names etc).
However, the bot doesnt seem to do anything (i'm trying it on a brand new acc).
And i get this error :
[31mERRO←[0m [extracts_v6.go:38] failed to parse planet infos: Couillizator [1:450:12]Forme de vie: Les Humains12.800km (0/163)-12 °C à 28°CVue d`ensembleRessourcesForme de vieRechercheInstallationsChantier spatialDéfenseFlotteGalaxie

Is it because like you've not done the parsing for V9 in french or something like that? Or did i do something wrong?
Thanks in advance!

**Comment by freesolotr** [comment]
I have the same problem with the Turkish language as well.

**Comment by malatia** [comment]
Well, if at least we could be sure it comes from the language, it would be a huge improvement :D

**Comment by kokiddp** [comment]
fixed in v0.2.58
