### ISSUE TITLE
Run multiple Instances of the script for different universes?

### ISSUE THREAD

**Issue by thstorm** [ogame-tbot/TBot#76]
Hi,

is the any possibility to run multiple instances of this script?
I want to run in for different universes in ogame.

When I put the script in different folder with separate settings.jar the secondly started script seems not to take "its" settings.jar

Any ideas?

**Comment by emilianosalatino** [comment]
You can run as many as you want. Just make sure you're changing the credential, use proxys for each and keep them in separate folders. If things aren't working revise settings.json

**Comment by emilianosalatino** [comment]
Also the settings extension is .json nor .jar

**Comment by thstorm** [comment]
Thanks for reply.

Do I need to have separate Accounts for this?
I tried to use the Same account with different universes.

**Comment by kokiddp** [comment]
you can use the same lobby account for different universes
you need different lobby accounts for multiple accounts on the same universe (you'll need proxies for that)
the golden rule is: 1 ip per account per universe

anyway, you need one port per instance, so remember to change the port in the settings for each instance (ie: 8080, 8081, 8082 etc...)
